import { MigrationInterface, QueryRunner } from 'typeorm';

const EXERCISE_NAME_TRANSLATIONS = [
  ['Barbell Bench Press', 'Жим штанги лежачи'],
  ['Incline Barbell Bench Press', 'Жим штанги на похилій лаві'],
  ['Decline Barbell Bench Press', 'Жим штанги на лаві з негативним нахилом'],
  ['Guillotine Press', 'Гільйотинний жим'],
  ['Reverse Grip Bench Press', 'Жим штанги лежачи зворотним хватом'],
  ['Floor Press (Barbell)', 'Жим штанги з підлоги'],
  ['Dumbbell Bench Press', 'Жим гантелей лежачи'],
  ['Incline Dumbbell Bench Press', 'Жим гантелей на похилій лаві'],
  ['Decline Dumbbell Bench Press', 'Жим гантелей на лаві з негативним нахилом'],
  ['Dumbbell Flys', 'Розведення гантелей лежачи'],
  ['Incline Dumbbell Flys', 'Розведення гантелей на похилій лаві'],
  ['Dumbbell Pullover', 'Пуловер з гантеллю'],
  ['Svend Press', 'Жим Свенда'],
  ['Hex Press (Squeeze Press)', 'Жим гантелей разом'],
  ['Cable Crossover (High to Low)', 'Кросовер у блоці зверху вниз'],
  ['Cable Crossover (Low to High)', 'Кросовер у блоці знизу вгору'],
  [
    'Standard Cable Flys (Middle)',
    'Розведення рук у кросовері на рівні грудей',
  ],
  ['Pec Deck Machine (Butterfly)', 'Зведення рук у тренажері Батерфляй'],
  ['Machine Chest Press (Seated)', 'Жим від грудей у тренажері сидячи'],
  ['Hammer Strength Chest Press', 'Жим від грудей у тренажері Hammer Strength'],
  ['Smith Machine Bench Press', 'Жим лежачи у тренажері Сміта'],
  ['Smith Machine Incline Press', 'Похилий жим у тренажері Сміта'],
  ['Push-Ups (Standard)', 'Віджимання класичні'],
  ['Wide Grip Push-Ups', 'Віджимання широким хватом'],
  ['Incline Push-Ups', 'Віджимання з руками на підвищенні'],
  ['Decline Push-Ups', 'Віджимання з ногами на підвищенні'],
  ['Dips (Chest Version)', 'Віджимання на брусах з акцентом на груди'],
  ['Plyometric Push-Ups', 'Пліометричні віджимання'],
  ['Pull-Up (Wide Grip)', 'Підтягування широким хватом'],
  ['Chin-Up', 'Підтягування зворотним хватом'],
  ['Neutral Grip Pull-Up', 'Підтягування нейтральним хватом'],
  ['Lat Pulldown (Wide Grip)', 'Тяга верхнього блока широким хватом'],
  [
    'Lat Pulldown (Close Grip V-Bar)',
    'Тяга верхнього блока вузьким хватом з V-рукояткою',
  ],
  ['Lat Pulldown (Reverse Grip)', 'Тяга верхнього блока зворотним хватом'],
  ['Single-Arm Lat Pulldown', 'Тяга верхнього блока однією рукою'],
  ['Straight-Arm Cable Pulldown', 'Тяга верхнього блока прямими руками'],
  ['Assisted Pull-Up Machine', 'Підтягування в тренажері з допомогою'],
  ['Bent Over Barbell Row', 'Тяга штанги в нахилі'],
  ['Pendlay Row', 'Тяга Пендлея'],
  ['Yates Row', 'Тяга Єйтса'],
  ['T-Bar Row', 'Тяга Т-грифа'],
  ['Landmine Row', 'Тяга landmine'],
  ['One-Arm Dumbbell Row', 'Тяга гантелі однією рукою'],
  ['Chest-Supported Dumbbell Row', 'Тяга гантелей з опорою грудьми'],
  ['Kroc Row', 'Тяга Крока'],
  ['Seated Cable Row (Close Grip)', 'Горизонтальна тяга блока вузьким хватом'],
  ['Seated Cable Row (Wide Grip)', 'Горизонтальна тяга блока широким хватом'],
  ['Machine Row', 'Тяга в тренажері'],
  ['Inverted Row (Bodyweight)', 'Австралійські підтягування'],
  ['Meadows Row', 'Тяга Медоуза'],
  ['Renegade Row', 'Тяга Ренегата'],
  ['Deadlift (Conventional)', 'Класична станова тяга'],
  ['Rack Pull', 'Тяга з рами'],
  ['Hyperextension (Back Extension)', 'Гіперекстензія'],
  ['Superman', 'Супермен'],
  ['Barbell Shrug', 'Шраги зі штангою'],
  ['Dumbbell Shrug', 'Шраги з гантелями'],
  ['Barbell Back Squat', 'Присідання зі штангою на спині'],
  ['Front Squat', 'Фронтальні присідання'],
  ['Leg Press', 'Жим ногами'],
  ['Hack Squat', 'Гак-присідання'],
  ['Leg Extension', 'Розгинання ніг у тренажері'],
  ['Bulgarian Split Squat', 'Болгарські спліт-присідання'],
  ['Goblet Squat', 'Гоблет-присідання'],
  ['Walking Lunge', 'Випади в ходьбі'],
  ['Reverse Lunge', 'Зворотні випади'],
  ['Step-Up', 'Зашагування на платформу'],
  ['Sissy Squat', 'Сіссі-присідання'],
  ['Pistol Squat', 'Присідання Пістолет'],
  ['Romanian Deadlift (Barbell)', 'Румунська тяга зі штангою'],
  ['Romanian Deadlift (Dumbbell)', 'Румунська тяга з гантелями'],
  ['Stiff-Leg Deadlift', 'Станова тяга на прямих ногах'],
  ['Lying Leg Curl', 'Згинання ніг лежачи'],
  ['Seated Leg Curl', 'Згинання ніг сидячи'],
  ['Nordic Hamstring Curl', 'Нордичне згинання ніг'],
  ['Glute-Ham Raise', 'Підйом корпусу для сідниць і біцепса стегна'],
  ['Good Morning', 'Нахили зі штангою Good Morning'],
  ['Barbell Hip Thrust', 'Хіп-траст зі штангою'],
  ['Glute Bridge', 'Сідничний місток'],
  ['Cable Pull-Through', 'Протяжка між ногами в кросовері'],
  ['Hip Abduction Machine', 'Відведення стегон у тренажері'],
  ['Sumo Deadlift', 'Станова тяга сумо'],
  ['Standing Calf Raise', 'Підйоми на носки стоячи'],
  ['Seated Calf Raise', 'Підйоми на носки сидячи'],
  ['Donkey Calf Raise', 'Підйоми на носки в нахилі'],
  ['Leg Press Calf Raise', 'Підйоми на носки в жимі ногами'],
  ['Hip Adduction Machine', 'Зведення стегон у тренажері'],
  ['Copenhagen Plank', 'Копенгагенська планка'],
  ['Overhead Barbell Press (Military Press)', 'Жим штанги над головою'],
  ['Seated Barbell Press', 'Жим штанги сидячи'],
  ['Seated Dumbbell Press', 'Жим гантелей сидячи'],
  ['Arnold Press', 'Жим Арнольда'],
  ['Push Press', 'Поштовховий жим'],
  ['Behind the Neck Press', 'Жим штанги з-за голови'],
  ['Machine Shoulder Press', 'Жим на плечі в тренажері'],
  ['Landmine Press', 'Жим landmine'],
  ['Handstand Push-Ups', 'Віджимання в стійці на руках'],
  ['Dumbbell Lateral Raise', 'Махи гантелями в сторони'],
  ['Cable Lateral Raise', 'Махи в сторони в кросовері'],
  ['Seated Lateral Raise', 'Махи в сторони сидячи'],
  ['Machine Lateral Raise', 'Махи в сторони в тренажері'],
  ['Egyptian Lateral Raise (Cable)', 'Єгипетські махи в сторони в кросовері'],
  ['Upright Row (Barbell)', 'Тяга штанги до підборіддя'],
  ['Upright Row (Cable)', 'Тяга блока до підборіддя'],
  ['Dumbbell Front Raise', 'Підйом гантелей перед собою'],
  ['Barbell Front Raise', 'Підйом штанги перед собою'],
  ['Plate Front Raise', 'Підйом диска перед собою'],
  ['Cable Front Raise', 'Підйом руки перед собою в кросовері'],
  [
    'Bent-Over Dumbbell Reverse Fly',
    'Розведення гантелей у нахилі на задні дельти',
  ],
  ['Reverse Pec Deck (Machine Fly)', 'Зворотний батерфляй у тренажері'],
  ['Cable Rear Delt Fly', 'Розведення рук у кросовері на задні дельти'],
  ['Face Pull', 'Тяга каната до обличчя'],
  ['Lying Face Pull', 'Тяга каната до обличчя лежачи'],
  [
    'External Rotation (Cable/Dumbbell)',
    'Зовнішня ротація плеча з блоком або гантеллю',
  ],
  [
    'Internal Rotation (Cable/Dumbbell)',
    'Внутрішня ротація плеча з блоком або гантеллю',
  ],
  ['Cuban Press', 'Кубинський жим'],
  ['Barbell Curl', 'Згинання рук зі штангою'],
  ['EZ Bar Curl', 'Згинання рук з EZ-грифом'],
  ['Reverse Grip Barbell Curl', 'Згинання рук зі штангою зворотним хватом'],
  ['Drag Curl', 'Згинання рук зі штангою вздовж корпусу'],
  ['21s (Barbell/EZ Bar)', 'Згинання 21 зі штангою або EZ-грифом'],
  ['Standing Dumbbell Curl', 'Згинання рук з гантелями стоячи'],
  ['Seated Dumbbell Curl', 'Згинання рук з гантелями сидячи'],
  ['Hammer Curl', 'Молоткові згинання'],
  ['Incline Dumbbell Curl', 'Згинання рук з гантелями на похилій лаві'],
  ['Concentration Curl', 'Концентроване згинання руки'],
  ['Zottman Curl', 'Згинання Зоттмана'],
  ['Alternating Dumbbell Curl', 'Почергове згинання рук з гантелями'],
  [
    'Preacher Curl (Barbell/EZ Bar)',
    'Згинання рук на лаві Скотта зі штангою або EZ-грифом',
  ],
  [
    'One-Arm Dumbbell Preacher Curl',
    'Згинання однієї руки з гантеллю на лаві Скотта',
  ],
  ['Spider Curl', 'Павукові згинання'],
  [
    'Cable Bicep Curl (Straight Bar)',
    'Згинання рук у кросовері з прямою рукояткою',
  ],
  ['Rope Hammer Curl', 'Молоткові згинання з канатом'],
  [
    'Bayesian Curl (Behind-the-back Cable Curl)',
    'Байєсівське згинання руки в кросовері за спиною',
  ],
  ['High Cable Curl (Crucifix Curl)', 'Згинання рук у верхніх блоках'],
  ['Single Arm Cable Curl', 'Згинання однієї руки в кросовері'],
  ['Machine Bicep Curl', 'Згинання рук у тренажері на біцепс'],
  ['Preacher Curl Machine', 'Згинання рук у тренажері Скотта'],
  ['Close-Grip Barbell Bench Press', 'Жим штанги лежачи вузьким хватом'],
  ['Dips (Triceps Focus)', 'Віджимання на брусах з акцентом на трицепс'],
  ['Weighted Bench Dip', 'Зворотні віджимання від лави з вагою'],
  ['JM Press', 'JM-жим'],
  ['Floor Press (Close Grip)', 'Жим з підлоги вузьким хватом'],
  ['Skullcrushers (EZ Bar)', 'Французький жим лежачи з EZ-грифом'],
  ['Skullcrushers (Dumbbell)', 'Французький жим лежачи з гантелями'],
  [
    'Dumbbell Rollback Extension',
    'Розгинання гантелей лежачи з відведенням назад',
  ],
  ['Tate Press', 'Жим Тейта'],
  [
    'Overhead Dumbbell Extension (Seated)',
    'Розгинання руки з гантеллю над головою сидячи',
  ],
  [
    'Overhead Dumbbell Extension (Standing)',
    'Розгинання руки з гантеллю над головою стоячи',
  ],
  [
    'Overhead Cable Extension (Rope)',
    'Розгинання рук над головою в кросовері з канатом',
  ],
  ['French Press (Standing EZ Bar)', 'Французький жим стоячи з EZ-грифом'],
  [
    'Triceps Cable Pushdown (Rope)',
    'Розгинання рук на трицепс у кросовері з канатом',
  ],
  [
    'Triceps Cable Pushdown (Straight Bar)',
    'Розгинання рук на трицепс у кросовері з прямою рукояткою',
  ],
  [
    'Triceps Cable Pushdown (V-Bar)',
    'Розгинання рук на трицепс у кросовері з V-рукояткою',
  ],
  [
    'Reverse Grip Cable Pushdown',
    'Розгинання рук у кросовері зворотним хватом',
  ],
  ['Single-Arm Cable Pushdown', 'Розгинання однієї руки в кросовері'],
  ['Cross-Body Cable Extension', 'Розгинання руки в кросовері через корпус'],
  ['Dumbbell Kickback', 'Відведення руки з гантеллю назад на трицепс'],
  ['Cable Kickback', 'Відведення руки назад у кросовері на трицепс'],
  ['Crunch', 'Скручування'],
  ['Decline Bench Crunch', 'Скручування на похилій лаві'],
  ['Cable Crunch (Kneeling)', 'Скручування в кросовері стоячи на колінах'],
  ['Machine Ab Crunch', 'Скручування в тренажері на прес'],
  ['GHD Sit-Up', 'Підйом корпусу на GHD'],
  ['V-Up', 'V-підйом'],
  ['Sit-Up', 'Підйом корпусу'],
  ['Hanging Leg Raise', 'Підйом ніг у висі'],
  ["Captain's Chair Leg Raise", 'Підйом ніг у капітанському кріслі'],
  ['Lying Leg Raise', 'Підйом ніг лежачи'],
  ['Reverse Crunch', 'Зворотні скручування'],
  ['Dragon Flag', 'Прапор дракона'],
  ['Flutter Kicks', 'Флатер-кіки'],
  ['Scissors', 'Ножиці'],
  ['Russian Twist', 'Російські скручування'],
  ['Cable Woodchopper', 'Дроворуб у кросовері'],
  ['Side Plank', 'Бічна планка'],
  ['Bicycle Crunch', 'Велосипедні скручування'],
  ['Side Bend (Dumbbell/Cable)', 'Бічні нахили з гантеллю або блоком'],
  ['Heel Touch', 'Дотики до п’ят'],
  ['Plank', 'Планка'],
  ['Ab Wheel Rollout', 'Ролик для преса'],
  ['Hollow Body Hold', 'Утримання hollow body'],
  ['Mountain Climber', 'Альпініст'],
  ['Vacuum', 'Вакуум'],
  ['Treadmill Run', 'Біг на біговій доріжці'],
  ['Treadmill Incline Walk', 'Ходьба на біговій доріжці з нахилом'],
  ['Elliptical Trainer', 'Еліптичний тренажер'],
  ['Stationary Bike (Spinning)', 'Велотренажер'],
  ['Recumbent Bike', 'Горизонтальний велотренажер'],
  ['Rowing Machine', 'Гребний тренажер'],
  ['Stair Climber (StairMaster)', 'Сходовий тренажер'],
  ['Assault Bike (Air Bike)', 'Ейрбайк'],
  ['SkiErg', 'Лижний ергометр SkiErg'],
  ["Jacob's Ladder", 'Тренажер Jacob’s Ladder'],
  ['Jump Rope', 'Стрибки зі скакалкою'],
  ['Double Unders (Jump Rope)', 'Подвійні стрибки зі скакалкою'],
  ['Burpees', 'Берпі'],
  ['Jumping Jacks', 'Джампінг-джек'],
  ['High Knees', 'Біг на місці з високим підніманням колін'],
  ['Box Jumps', 'Стрибки на тумбу'],
  ['Mountain Climbers', 'Альпіністи'],
  ['Running (Outdoor)', 'Біг на вулиці'],
  ['Sprinting', 'Спринт'],
  ['Battle Ropes', 'Бойові канати'],
  ['Sled Push (Prowler)', 'Штовхання саней'],
  ['Heavy Bag Workout', 'Робота на важкому мішку'],
  ['Shadow Boxing', 'Бій з тінню'],
  ['Bear Crawl', 'Ведмежа хода'],
  ['Clean and Jerk', 'Поштовх штанги'],
  ['Snatch', 'Ривок штанги'],
  ['Power Clean', 'Підйом штанги на груди в силовому стилі'],
  ['Hang Clean', 'Підйом штанги на груди з вису'],
  ['Clean High Pull', 'Висока тяга штанги на груди'],
  ['Kettlebell Swing (Russian)', 'Махи гирею до рівня плечей'],
  ['Kettlebell Swing (American)', 'Махи гирею над головою'],
  ['Turkish Get-Up', 'Турецький підйом'],
  ['Kettlebell Snatch', 'Ривок гирі'],
  ['Kettlebell Clean & Press', 'Підйом гирі на груди та жим'],
  ['Thruster (Barbell)', 'Трастер зі штангою'],
  ['Thruster (Dumbbell)', 'Трастер з гантелями'],
  ['Devil Press', 'Девіл-прес'],
  ['Man Maker', 'Мен-мейкер'],
  ['Wall Ball', 'Кидки медбола в стіну'],
  ['Cluster', 'Кластер зі штангою'],
  ["Farmer's Walk", 'Фермерська хода'],
  ['Yoke Walk', 'Хода з коромислом'],
  ['Tire Flip', 'Перекидання шини'],
  ['Sled Pull', 'Тяга саней'],
  ['Atlas Stone Lift', 'Підйом каменя Атласа'],
  ['Muscle-Up (Bar)', 'Вихід силою на перекладині'],
  ['Muscle-Up (Rings)', 'Вихід силою на кільцях'],
] as const;

export class TranslateExerciseNamesToUkrainian1775594552511 implements MigrationInterface {
  name = 'TranslateExerciseNamesToUkrainian1775594552511';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const [englishName, ukrainianName] of EXERCISE_NAME_TRANSLATIONS) {
      await queryRunner.query(
        `UPDATE "exercises"
         SET "name" = $1, "updatedAt" = now()
         WHERE "name" = $2
           AND NOT EXISTS (
             SELECT 1
             FROM "exercises"
             WHERE "name" = $1
           )`,
        [ukrainianName, englishName],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    for (const [englishName, ukrainianName] of EXERCISE_NAME_TRANSLATIONS) {
      await queryRunner.query(
        `UPDATE "exercises"
         SET "name" = $1, "updatedAt" = now()
         WHERE "name" = $2
           AND NOT EXISTS (
             SELECT 1
             FROM "exercises"
             WHERE "name" = $1
           )`,
        [englishName, ukrainianName],
      );
    }
  }
}
